repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/python/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
              setup.cfg|
              trojsten/static/.*
          )$
      - id: mixed-line-ending
      - id: trailing-whitespace
# TODO fix problems and uncomment
#   - repo: https://github.com/pycqa/flake8
#     rev: 4.0.1
#     hooks:
#     -   id: flake8
